### ISSUE TITLE
Configuration per project

### ISSUE THREAD

**Issue by georgecoca** [b-sharpe/SlackStorm#2]
Hi. I know I opened a previous issue regarding this, but this one is different. It will be nice if we can have a slack configuration per project related to a team.

Current workflow:
You can register multiple channels (they are visible on all projects opened in Phpstorm).

Proposed workflow:
Associate/register a team for project. In that team I can register multiple channels. So when you right-click the selected code, it will be displayed all channels registered for that team (no team required to select, just the channels).

Let me know your thoughts :)

**Comment by b-sharpe** [comment]
From what I can see this is not possible. You CAN do a channel override in an incoming webhook, but it has to be a public channel within that team's token and there is no way to list them out so a user would still need to add each channel manually. Let me know if I'm misunderstanding this or you have an idea how to accomplish this, I'm open to ideas.

As for why I allowed global access to configured channels rather than per-project, the majority of developers (including myself and my team) don't share a PC, and may have channels shared between projects depending on who is on a team. For example, myself and a couple team members share one/two channels for code snippets across about 4/5 different projects, if we stored these at a project level we would need to add the channels for each. I also have a generic channel that I sometimes post to, and have in total about 20-30 different projects open at any given time so it's more convenient to have them available across all projects.

**Comment by b-sharpe** [comment]
Closing. Re-open to further disccussion
