### ISSUE TITLE
Expand settings

### ISSUE THREAD

**Issue by kevinquillen** [b-sharpe/SlackStorm#9]
Would it be possible to add configuration to control the color of the posted message (instead of grey) as well as optionally change the title of the attachment? It would also be great to edit the config of one channel at a time instead of reset all.

Great work by the way, so handy.

**Comment by BearOutThere** [comment]
Hi Kevin,  since you posted after me i assume that you installed SlackStorm recently.  Just trying to confirm my issue.  After installation did you see SlackStrom options in the Tools menu as the documentation states?  I don't see that option and can't configure the channel.

**Comment by b-sharpe** [comment]
Hey Kevin. 

The colour doesn't really do anything other than put a line down the side (see screenshot) since this is pretext. Unfortunately there is no way at this time to hook into Slack's text snippets so we can't make use of code beautification. I spoke with Slack developers about this and they only release the full API to "Official Product Developers", so until I get on the JetBrains team, we're stuck :smile: 

I can however look into the other two. For the title, it currently outputes filename/line numbers, were you thinking override the title all together or have an option to append? Also, make sure you are using the latest version as you should no longer have to "reset all" but rather just delete and readd a specific channel. That said, I do plan on a 'Edit channel' option.

![capture](https://cloud.githubusercontent.com/assets/12438512/13291045/2df9c7c4-dacb-11e5-8c18-5465920f8407.PNG)

**Comment by iberflow** [comment]
Hi guys,

Awesome plugin! I was wondering whether it's possible to display a full namespace if one is present rather than just the filename. I'm not sure how to achieve that since I haven't worked with java for years. Took a quick look at the Intellij docs but couldn't find a similar method in FileDocumentManager class.

**Comment by b-sharpe** [comment]
This is being worked on. Trying to sort out string length issues and relative directories to your project rather than your system root

**Comment by b-sharpe** [comment]
@ignasbernotas full namespace in latest release
